### ISSUE TITLE
csv writing issues

### ISSUE THREAD

**Issue by charliwest** [DottoreTozzi/iSpindel-TCP-Server#1]
I was just about to post an issue on the iSpindel github but noticed it moved here.

I have been trying to get this to write out to a csv file but keep getting this error.

`('192.168.178.207', 16534) Input Str is now:{
('192.168.178.207', 16534) received:'"name":"iSpindel000","ID":3765177,"angle":83.31707,"temperature":21.4375,"battery":3.837331,"gravity":30.20167}\r\n'
('192.168.178.207', 16534) Input Str is now:{"name":"iSpindel000","ID":3765177,"angle":83.31707,"temperature":21.4375,"battery":3.837331,"gravity":30.20167}
('192.168.178.207', 16534) iSpindel000 (ID:3765177) : Data received OK.
('192.168.178.207', 16534) - closed connection
('192.168.178.207', 16534) - writing CSV
('192.168.178.207', 16534) CSV Error: coercing to Unicode: need string or buffer, int found`

Not sure if I can configured something wrong, it will send to ubidots fine.

**Comment by charliwest** [comment]
believe fixed by [this pull request](https://github.com/DottoreTozzi/iSpindel-TCP-Server/pull/2)

**Comment by DottoreTozzi** [comment]
Thank you, I have merged this. Sorry for the delay.
