### ISSUE TITLE
Add MQTT forward?

### ISSUE THREAD

**Issue by fodi666** [DottoreTozzi/iSpindel-TCP-Server#12]
Hi,

Do you think it would be possible to add an MQTT publish option as a forward method to the script? I would like to connect the iSpindel to Home Assistant and that might be a good candidate for the interface. Home Assistant does have an [MQTT broker](https://www.home-assistant.io/docs/mqtt/broker#embedded-broker) that could be used.

Thanks

**Comment by DottoreTozzi** [comment]
I'll look into it.
Should be quite straight-forward.

**Comment by fodi666** [comment]
I have sent you an email about this.

**Comment by DottoreTozzi** [comment]
Didn't receive your Email. Can you send it again, plz?

**Comment by fodi666** [comment]
https://gist.github.com/fodi666/2d933a8e5cecbaa2abf501a118c28d9d
I have added an MQTT forwarding option to your original script, so it can forward the iSpindel data to Home Assistant or other applications using the MQTT protocol. It just forwards the same JSON you create for other services as well and it supports using an anonymous or an authenticated publish. It uses the Paho-MQTT package. My additions are not that nice, but they work. (This was my first work in Python.) It could definitely use some more feedback on the connection from Paho for the debugging view.

**Comment by FernandoGarcia** [comment]
Hi!

You could make a pull request for it.

Best regards.

**Comment by DottoreTozzi** [comment]
Yes, please.
