### ISSUE TITLE
iSpindel Konfiguration

### ISSUE THREAD

**Issue by LucLN** [DottoreTozzi/iSpindel-TCP-Server#14]
Hi,
wie konfiguriere ich die iSpindel um diesen Server zu nutzen?
Übersehe ich das Offensichtliche?
Danke.
Luc.

**Comment by DottoreTozzi** [comment]
Sorry für die späte Antwort.
Die iSpindel muss auf "TCP" konfiguriert werden, dann die IP Adresse des Servers eintragen und Port 9501.
