### ISSUE TITLE
nearly there

### ISSUE THREAD

**Issue by blucmal** [DottoreTozzi/iSpindel-TCP-Server#16]
I have the server recieving data but I have two issues when trying to write the csv file I have permission error when I try to create the script user I get 

> MariaDB [(none)]> CREATE USER 'iSpindle'@'localhost' IDENTIFIED BY 'password';
> ERROR 1396 (HY000): Operation CREATE USER failed for 'iSpindle'@'localhost'
> MariaDB [(none)]> GRANT ALL PRIVILEGES ON iSpindle . * TO 'iSpindle'@'localhost'

and then when I try to add the table I get 

> 
>  -> COLLATE=ascii_bin COMMENT='iSpindle Data';
> ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''Data' (
> 'Timestamp' datetime NOT NULL,
> 'Name' varchar(64) COLLATE ascii_bin NOT' at line 1
> MariaDB [(none)]> 

any ideas?

**Comment by DottoreTozzi** [comment]
Please try and copy/paste the commands exactly as in INSTALL_en.md.
