### ISSUE TITLE
Have both chartvalue and curent value on same page?

### ISSUE THREAD

**Issue by tonarii** [DottoreTozzi/iSpindel-TCP-Server#19]
Hi, first thanks for thoses great files !
I'm working on a dashboard, and on the main page, i would like to show both a charvalue with tilt and temp on a line graph and on two other charts the current temp and the current tilt (liek a gauge or something like that).
But i'm having an issue with "i think" those parts :
list($time, $temperature, $angle, $battery) = getCurrentValues($conn, $_GET['name']);
list($angle, $temperature) = getChartValues($conn, $_GET['name'], $timeFrame, $_GET['reset']);
How can i have both on the same page ?
Thanks.

**Comment by DottoreTozzi** [comment]
Take a look at status.php and battery.php for examples on how to do a gauge chart.
And when done, don't forget to send me your code so I can include it here. :)

**Comment by tonarii** [comment]
Hi thanks for your answer and for you work !
Actually i'm building a dashboard, and i'm not using your ispindel.py, beacause i don't know how to use it on my online website or server (ovh) ^^
But i use almost everything else.
I have a php file to send the data to my online database, and everything is also online on my personal website ftp.
So it's king of a mix of too many things... 
I'm not a dev, so i must have done some bad integration, i don't have all the ispindel informations on my database.
I don't have the RSSi value and also no ID. 
I run the last firmware on my device.
Here is what i have on my index.php (the file my ispindel connect to) :
`$sql = 'INSERT INTO Data (Timestamp, Name, ID, Angle, Temperature, Battery, ResetFlag, Gravity, UserToken, "Interval", RSSI)`

`VALUES ("'.$date.'", "'.$data->name.'", "'.$data->id.'", "'.$data->angle.'", "'.$data->temperature.'", "'.$data->battery.'", "'.$data->resetflag.'", "'.$data->gravity.'", "'.$data->usertoken.'", "'.$data->interval.'", "'.$data->rssi.'")';`

I used your database model to create it.

**Comment by DottoreTozzi** [comment]
Well, seeing that you use my database model, but not my code, I guess, there's not really anything I can do for you...(?)
RSSI and Interval should be transmitted properly, so this must have to do with your php script (which I have nothing to do with).
