### ISSUE TITLE
Remote config does not work ?

### ISSUE THREAD

**Issue by Misenkooo** [DottoreTozzi/iSpindel-TCP-Server#25]
Hi guys, it's only me or the remote configuration does not work in latest iSpindel firmware ?
I can see in server logs that new configuration has been sent in TCP response but iSpindel just ignores it and don't change anything.
Thanks.

**Comment by DottoreTozzi** [comment]
It will be best to bring up this issue with Sam.
The current release version of the firmware still seems to ignore the config being sent.
