### ISSUE TITLE
Problems with php7

### ISSUE THREAD

**Issue by PjotrekSE** [DottoreTozzi/iSpindel-TCP-Server#4]
Now that Raspberry Pi only installs php7, many mysql calls must be replaced by mysqli calls. The problem there is that they require different, additional parameters. This leads to the diagram pages don't work any more. The include files unfortunately need substantial rework.

**Comment by DottoreTozzi** [comment]
Have you tried after the last commit? This should be already fixed.
At least it's working here, installed on latest "naked" Raspbian Stretch.
The installation guide has been updated as well.

**Comment by PjotrekSE** [comment]
Well. Now it worx, but I had to change pw in the file, since it no longer fetches it from the database.

**Comment by DottoreTozzi** [comment]
Now you've lost me... ????
There never was an INI file. That's something I have planned for the future.
The whole config will actually end up within the database, eventually.

But I have not changed anything but to replace the mysql calls with their mysqli equivalents.
The database password has always defined in common_db.php, so far...

**Comment by PjotrekSE** [comment]
Tut mir Leid. My mistake. Danke ebenfalls.
Es hat mir so erstaunt daß alles andere hat direkt funktioniert. Das war
nicht meiner Erfahrung aus der Branche.
Peter Kling
PjotrekSE
Ex Nixdorfer SystemSpezi

Den 11 dec 2017 00:43 skrev "Stephan Schreiber" <notifications@github.com>:

**Comment by DottoreTozzi** [comment]
Thank you, and no problem!
Glad it works for you. This is just the initial stage of a project I intend to improve a lot over the next weeks and months.
In its current stage it mostly reflects what I wanted most urgently for myself.
Usability and flexibility will be improved. Stay tuned!
