### ISSUE TITLE
Home icon missing

### ISSUE THREAD

**Issue by mcmellow** [DottoreTozzi/iSpindel-TCP-Server#42]
Hi,  it is not a big deal just cosmetic. but the **icons8-home-26.png**  file is missing in /web/include/

Kind regards
McMelloW

**Comment by avollkopf** [comment]
This might be a commercial problem. I have also added the functionality that buttons can show up as icons if the corresponding icons are in the /include folder. I will have a look, that a button is shown, if no png file is in the folder.

**Comment by avollkopf** [comment]
It can be easiliy fixed if two lines are added to the diagram scripts below the get fields from database section:
$file = "settings";
$stop = get_field_from_sql($conn,$file,"stop");

At the end, the link needs to be adapted (alt="..." added):

`<a href=/iSpindle/index.php><img src=include/icons8-home-26.png alt="<?php echo $stop; ?>"></a>
`
If no png file is in the /include directory, 'Back' is shown in the selected language.

**Comment by mcmellow** [comment]
Thanks for the work around solution. 

I think the line $file = "settings";  should be changed to **$file = "Strings";**
