### ISSUE TITLE
iSpindle.py 1.4.0

### ISSUE THREAD

**Issue by PjotrekSE** [DottoreTozzi/iSpindel-TCP-Server#7]
Need str() on lines 157 and 158 in csv handling of new data.
Ubidots gives error code 400 on user_token in line 253:  
"usertoken": [{"status_code": 400, "errors": {"value": ["A valid number is required."]}}]

**Comment by DottoreTozzi** [comment]
Nice catch!
User Token should not be transmitted to Ubidots so I removed it.
Can you please try again with the latest commit?

**Comment by PjotrekSE** [comment]
Worx fine now. Thanx!
